[project]
name = "gr3nja_discord_bot"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
authors = [{ name = "Gr3nja" }]
dependencies = []

[project.urls]
Homepage = "https://github.com/Gr3nja/Gr3njaDiscordBot"
Issues = "https://github.com/Gr3nja/Gr3njaDiscordBot/issues"
